[versions]
android-compileSdk = "35"
android-minSdk = "21"
android-targetSdk = "35"
kotlin = "1.9.25"
android-gradle-plugin = "8.6.0"
dokka = "1.9.20"
androidx-lifecycle = "2.8.7"
androidx-camera = "1.4.0"
androidx-fragment = "1.8.5"
androidx-test = "1.6.1"
androidx-test-runner = "1.6.2"
androidx-test-junit = "1.2.1"
kotlinx-coroutines = "1.7.3"
koin = "2.2.3"
moshi = "1.15.1"
mockito = "5.12.0"
espresso = "3.6.1"
checkstyle = "7.8.2"
pmd = "6.0.0"
jacoco = "0.8.10"
hilt = "2.46.1"
navigation_component = "2.8.4"
compose-bom = "2024.06.00"
accompanist-themeAdapter = "1.1.1"
compose-activity = "1.9.3"
koin-bom = "3.5.6"
orbitMvi = "9.0.0"
core-ktx = "1.14.0-alpha01"
multidex = "2.0.1"
androidx-activity = "1.9.3"
appcompat = "1.7.0"
coordinatorlayout = "1.2.0"
constraintlayout = "2.2.0"
viewpager = "1.0.0"
viewpager2 = "1.1.0"
recyclerview = "1.3.2"
cardview = "1.0.0"
annotation = "1.9.1"
orchestrator = "1.5.1"
uiautomator = "2.3.0"
google-material = "1.12.0"
chrisbanes-insetter = "0.6.1"
chrisbanes-photo-view = "2.3.0"
mockito-kotlin-version = "4.0.0"
mockito-kotlin2-version = "2.2.0"
io-mockk = "1.12.2"
cash-turbine = "0.12.3"
junit-testing = "4.13.2"
detekt = "1.23.6"
ktlint = "10.2.0"
mlkit-barcode = "18.3.1"
mlkit-text-recognition = "19.0.1"
apache-imaging = "1.0-alpha2"
jersey-futures = "2.25.1"
google-truth = "1.1.3"
robo = "4.14.1"
karumi-dexter = "6.2.3"
logback-core-classic = "1.1.1-6"
slf4j = "1.7.36"
ben-manes-gradle-versions = "0.39.0"
android-trustkit = "1.1.5"
android-lottie = "5.1.1"
j-unit-params = "1.1.1"
squareup-retrofit = "2.11.0"
squareup-okhttp3 = "4.12.0"
squareup-okio = "3.9.1"
logging-interceptor-okhttp3 = "4.12.0"
squareup-javapoet = "1.13.0"
cyclonedx = "1.8.1"
cyclonedx-core = "8.0.3"
json = "20240303"
datastore = "1.1.2"
org-tomlj = "1.1.1"
hiya-android="0.2"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-kotlinAsJava = { module = "org.jetbrains.dokka:kotlin-as-java-plugin", version.ref = "dokka" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
androidx-test-espresso-idlingresource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
koin-androidx-scope = { module = "io.insert-koin:koin-androidx-scope", version.ref = "koin" }
koin-androidx-viewmodel = { module = "io.insert-koin:koin-androidx-viewmodel", version.ref = "koin" }
koin-androidx-fragment = { module = "io.insert-koin:koin-androidx-fragment", version.ref = "koin" }
material = { module = "com.google.android.material:material", version.ref = "google-material" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "chrisbanes-insetter" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "chrisbanes-photo-view" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin-version" }
mockito-kotlin2 = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito-kotlin2-version" }
mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "io-mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "cash-turbine" }
junit = { module = "junit:junit", version.ref = "junit-testing" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
mlkit-barcodescanning = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "mlkit-barcode" }
mlkit-textrecognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "mlkit-text-recognition" }
apachecommons-imaging = { module = "org.apache.commons:commons-imaging", version.ref = "apache-imaging" }
completableFuture = { module = "org.glassfish.jersey.bundles.repackaged:jersey-jsr166e", version.ref = "jersey-futures" }
truth = { module = "com.google.truth:truth", version.ref = "google-truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robo" }
dexter = { module = "com.karumi:dexter", version.ref = "karumi-dexter" }
logback-android-core = { module = "com.github.tony19:logback-android-core", version.ref = "logback-core-classic" }
logback-android-classic = { module = "com.github.tony19:logback-android-classic", version.ref = "logback-core-classic" }
jacocoAndroid = { module = "com.hiya:jacoco-android", version.ref = "hiya-android" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
benManesVersions-gradle = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "ben-manes-gradle-versions" }
trustkit = { module = "com.datatheorem.android.trustkit:trustkit", version.ref = "android-trustkit" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "android-lottie" }
jUnitParams = { module = "pl.pragmatists:JUnitParams", version.ref = "j-unit-params" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup-retrofit" }
retrofit-moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "squareup-retrofit" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp3" }
okio = { module = "com.squareup.okio:okio", version.ref = "squareup-okio" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor-okhttp3" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
java-poet = { module = "com.squareup:javapoet", version.ref = "squareup-javapoet" }
cyclonedx-gradle = { module = "org.cyclonedx:cyclonedx-gradle-plugin", version.ref = "cyclonedx" }
cyclonedx-core-java = { module = "org.cyclonedx:cyclonedx-core-java", version.ref = "cyclonedx-core" }
jsonJava = { module = "org.json:json", version.ref = "json" }
navigation_fragment_ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation_component" }
navigation_ui_ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation_component" }
navigation_safe_args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation_component" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "org-tomlj" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-tools-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-tools-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
accompanist-themeAdapter = { module = "com.google.android.material:compose-theme-adapter-3", version.ref = "accompanist-themeAdapter" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
orbitmvi-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbitMvi" }
orbitmvi-test = { group = "org.orbit-mvi", name = "orbit-test", version.ref = "orbitMvi" }
orbitmvi-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbitMvi" }