# Disabled until we find a way to avoid manually appending "-SNAPSHOT" to versions after every release.
# Or we find a way to inject the version as a gradle property ONLY for the module we are releasing.

# name: Release snapshot of Merchant SDK

# on:
#   pull_request:

# jobs:
#   release-snapshot:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3

#       - name: setup java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'
#           cache: 'gradle'

#       - name: setup ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: '3.2.0'
#           bundler-cache: true

#       - name: "publish to gini's maven snapshots repo at https://repo.gini.net/nexus/content/repositories/snapshots"
#         uses: maierj/fastlane-action@v3.0.0
#         with:
#           lane: 'publish_to_maven_snapshots_repo'
#           options: >
#             { 
#               "repo_url": "https://repo.gini.net/nexus/content/repositories/snapshots",
#               "repo_user": "jenkins",
#               "repo_password": "${{ secrets.GINI_EXTERNAL_NEXUS_PASSWORD }}",
#               "project_id": "merchant-sdk",
#               "module_id": "sdk",
#               "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
#               "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
#             }

#       - name: "publish to Maven Central snapshots repo at https://oss.sonatype.org/content/repositories/snapshots/"
#         uses: maierj/fastlane-action@v3.0.0
#         with:
#           lane: 'publish_to_maven_snapshots_repo'
#           options: >
#             {
#               "repo_url": "https://oss.sonatype.org/content/repositories/snapshots/",
#               "repo_user": "alpar.gini",
#               "repo_password": "${{ secrets.MAVEN_CENTRAL_PASSWORD }}",
#               "project_id": "merchant-sdk",
#               "module_id": "sdk",
#               "signing_key_base64": "${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_BASE64 }}",
#               "signing_password": "${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}"
#             }
